/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author anibal
 */
public class frmTransport extends javax.swing.JFrame {

    /**
     * Creates new form frmTransporte
     */
    public frmTransport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbTransportType = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Transportation management form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(373, 18, 418, 65);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Transport data:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(133, 114, 147, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Base rate");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(133, 241, 120, 25);
        getContentPane().add(txtCode);
        txtCode.setBounds(308, 151, 121, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Transport Code:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(166, 151, 124, 25);

        cmbTransportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicycle", "Scooter", "Skates" }));
        cmbTransportType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTransportTypeItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbTransportType);
        cmbTransportType.setBounds(308, 201, 121, 22);

        txtPrice.setText("3000.0");
        getContentPane().add(txtPrice);
        txtPrice.setBounds(308, 245, 121, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("Transport Type:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(133, 197, 120, 25);

        btnAdd1.setText("Add");
        getContentPane().add(btnAdd1);
        btnAdd1.setBounds(140, 310, 83, 38);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(590, 100, 30, 227);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTransportTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTransportTypeItemStateChanged
        if (cmbTransportType.getSelectedItem() != null) {
            String selectedTransportType = cmbTransportType.getSelectedItem().toString();
            double price = 0.0; // Puedes establecer un valor predeterminado

            // Determina el precio basado en el tipo de transporte seleccionado
            if (selectedTransportType.equals("Bicycle")) {
                price = 3000.0; // Precio de una bicicleta
            } else if (selectedTransportType.equals("Scooter")) {
                price = 2000.0; // Precio de un scooter
            } else if (selectedTransportType.equals("Skates")) {
                price = 1500.0; // Precio de patines
            }

            txtPrice.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_cmbTransportTypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JComboBox<String> cmbTransportType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
